---
output:
  pdf_document:
    includes:
      keep_tex: yes
    number_sections: yes
---

```{r settings, include = FALSE}
knitr::opts_chunk$set(echo=TRUE, include=TRUE)
set.seed(1)
```
\newif\ifsol
\soltrue
\pagestyle{empty}
18\. Consider a rock whose U-Th-He age is `r tHe` Ma. Suppose that the
following data were acquired on the same sample:
   ```{r include=TRUE, echo=FALSE, results='asis'}
   knitr::kable(thermotab)
   ```
   Assuming that the ^36^Ar is of atmospheric origin (with
   ^40^Ar/^36^Ar~atm~=298.5), and using the notes for decay constants etc.,
   summarise the geological history of the sample.
   ```{r}
   # suppose that the data are in a table called tab:
   J <- tab[1]
   Ar96 <- tab[2]
   Ar06 <- tab[3]
   Ar06a <- 298.5
   zeta <- tab[4]
   rhoD <- tab[5]
   Ns <- tab[6]
   Ni <- tab[7]
   tHe <- 50
   Ar09r <- (Ar06-Ar06a)/Ar96 # radiogenic Ar40/Ar39 ratio
   tArAr <- log(1+J*Ar09r)/l40
   g <- 0.5
   tFT <- log(1+g*l38*zeta*1e-6*rhoD*Ns/Ni)/l38
   message('t(Ar-Ar)=',signif(tArAr,3),'=',
   't(FT)=',signif(tFT,3),'=',
   't(U-Th-He)=',tHe,', suggesting rapid cooling')
   ```
